### ISSUE TITLE
Speckle_Toolkit: implement the Delete() if doable

### ISSUE THREAD

**Issue by alelom** [BHoM/Speckle_Toolkit#11]
1. See if Speckle allows deletion of specific objects from a Stream.
1. The same, but with Children streams ("Clones" in the Speckle Viewer).
1. Implement them in the `Delete()` CRUD method of the Speckle_Toolkit adapter.

@PaulPoinet could you have a look at point 1 and 2?

**Comment by PaulPoinet** [comment]
Yes it's definitely possible
1. => https://speckleworks.github.io/SpeckleSpecs/#objectdelete
2. => https://speckleworks.github.io/SpeckleSpecs/#streamdelete

**Comment by alelom** [comment]
@PaulPoinet great! Thanks for the support :)
However:
> 2. => https://speckleworks.github.io/SpeckleSpecs/#streamdelete
this seems to delete a whole Stream -- not something we're interested in.

For 2), we basically need to know if 
> 1. => https://speckleworks.github.io/SpeckleSpecs/#objectdelete
is also applicable to Children streams.

**Comment by PaulPoinet** [comment]
I might be wrong, but I think there is no fundamental difference between a Stream and a child Stream (which is merely a Stream but just referenced as child to another Stream).
From a Stream, it is possible to check if it has Children, and then iterate through them and call `streamdelete` if wanted.
In that sense, all methods such has `objectdelete` are applicable to children streams (which are just streams). @didimitrie please correct me if I say bs

**Comment by PaulPoinet** [comment]
To access the Speckle create, delete functions, you can call them from the client object as
`SpeckleClient = new SpeckleApiClient()`
and do

- `SpeckleClient.ObjectDeleteAsync` to delete objects
- `SpeckleClient.StreamDeleteAsync` to delete streams
- etc...

![2019-06-06 (1)](https://user-images.githubusercontent.com/22736626/59051499-efb22180-8884-11e9-89b2-bb8796d759cb.png)

**Comment by didimitrie** [comment]
re (1) and (2) once you have a stream, you can always send a PUT request to the api with modified stream properties as you see fit. That's the [stream update](https://speckleworks.github.io/SpeckleSpecs/#streamupdate) api call. 

The methods @PaulPoinet brought up are DELETE requests, which remove the specified resource from the db.

**Comment by alelom** [comment]
> re (1) and (2) once you have a stream, you can always send a PUT request to the api with modified stream properties as you see fit. That's the stream update api call.

Thanks @didimitrie.
Based on what you also said [here](https://github.com/BHoM/Speckle_Toolkit/issues/16#issuecomment-500434818), I'm trying to figure out if I need to re-upload (update) the whole stream in order to modify it.
In short, is it possible to modify only certain objects contained in the stream, like removing them from the stream, without having to PUT also everything else?

**Comment by alelom** [comment]
* to modify only property X of a stream, create a new one in c#, populate just that property, and use that object for the put request; all the other fields can stay non-existant
* there used to operation endpoints for the list of objects specifically, but Dimitrie removed those from the api
