### ISSUE TITLE
Speckle_Toolkit: see how to ask Speckle to clone the stream

### ISSUE THREAD

**Issue by alelom** [BHoM/Speckle_Toolkit#15]

**Comment by PaulPoinet** [comment]
basically:
`SpeckleClient = new SpeckleApiClient() { BaseUrl = SpeckleAccount.RestApi, AuthToken = SpeckleAccount.Token, Stream = SpeckleStreamParent };
SpeckleClient.StreamCloneAsync`

**Comment by didimitrie** [comment]
I think you still need to pass a streamId. The gh client does it like this: 

https://github.com/speckleworks/SpeckleRhino/blob/dev/SpeckleGrasshopper/BaseComponents/GhSenderCoreClient.cs#L411-L419

It then also broadcasts an event (to do that you have to previously join the "resource" room, but that's another story).
