### ISSUE TITLE
Speckle_Toolkit: see if it's possible to set the _id to the objects when exporting them

### ISSUE THREAD

**Issue by alelom** [BHoM/Speckle_Toolkit#16]
Basically, if it's possible to define these:
![image](https://user-images.githubusercontent.com/6352844/59190476-b9222280-8b74-11e9-8c0c-3113ee4b1323.png)

**Comment by didimitrie** [comment]
Nope, that's the role of the database! You never ever ever never should make those yourself. If you want to assign objects to a stream, you create the objects first, save them, and then use those IDs to create placeholders which you put in the streams object list. 

What's the use case and context around this, so I can provide a better answer?

**Comment by alelom** [comment]
Thanks @didimitrie. 

I'm trying to see whether we can tell which BHoMObject is which in the Speckle export, in order to e.g. know what's been exported already and does not need re-exporting.
To do that, normally the BHoM relies on one of the following:
  1. being able to assign the ID in the external software, so it knows which object exist already and which is which
  2. relies on the fact that the external program defines the ids _progressively_ **and** on the fact that objects are exported in the order they are specified (syncronously) so it can guess the assigned id

>  you create the objects first, save them, and then use those IDs to create placeholders which you put in the streams object list.

this seems good enough to do option 1. Could you give me an example implementation?

**Comment by didimitrie** [comment]
Sure, generally this method can be a good reference (the gh `SendUpdate`): 

https://github.com/speckleworks/SpeckleRhino/blob/dev/SpeckleGrasshopper/BaseComponents/GhSenderCoreClient.cs#L723-L875

You can also see the placeholders being created here, together with the final PUT payload for the stream: 

https://github.com/speckleworks/SpeckleRhino/blob/fc153056a949636bd1fc4fa07b70061dfbfe8cf6/SpeckleGrasshopper/BaseComponents/GhSenderCoreClient.cs#L846-L856

Overall the flow of that method is: 

- get the object i need to send
- convert them so i can diff them up
- pass that through the local cache (which will purge perviously sent objects)
- orchestrate api calls to save those new objects in batches of 500kb or thereabouts
- save the newly sent objects in the local cache 
- map the `_id` gotten from the speckle server to the original objects
- create the placeholder array
- save it to the stream

It's a bit convoluted, i'll grant you that; it can be done much easier, but all this extra convolution was mostly added to optimise for speed/transaction cost. 

Anyway, if you have different ids, you can either keep track of that matching locally or maybe you could add the bhom id in a custom property of the speckle object? 

I haven't had much success with setting ids in host software, so i'm usually relying on "shadow" copies of the state (which i persist with the file). Not sure this helps :/
