### ISSUE TITLE
Speckle_Toolkit: Update AssemblyFileVersion to 3.1.0.0

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Speckle_Toolkit#41]
#### Description:
Update toolkit assembly file versions to the new milestone - file assembly version should now be 3.1.0.0

**To be done by 10th January 2020**

**Comment by FraserGreenroyd** [comment]
@alelom has this not been done? I can see the commits mentioning it but did it not get closed out by a PR? ❓

**Comment by alelom** [comment]
Yes this was done. I forgot to tag the issue.
