### ISSUE TITLE
Update copy locals and remove reference to common/unused items

### ISSUE THREAD

**Issue by rwemay** [BHoM/Speckle_Toolkit#83]
#### Description:

A lot of dlls go into the Build folder on build, can we check and make sure copy local is set to false for everything not needed, and remove old/unused references?

**Comment by alelom** [comment]
Thanks Rob. There were a couple of copy locals that I got rid of in https://github.com/BHoM/Speckle_Toolkit/pull/82.

However, I presume you refer to these:
![image](https://user-images.githubusercontent.com/6352844/80801321-de13ef80-8ba3-11ea-80f6-5484d9b8912a.png)

these are brought as dependencies by SpeckleCore. Currently it's really tricky to get rid of them.
